---
# defaults file for dot

dot_temp_dir: /tmp

dot_git_repo: "https://github.com/jiholland/dotprofiles.git"
dot_git_version: main
dot_git_accept_newhostkey: true

dot_bash_profiles:
  - "bash_profile"
  - "bashrc"
  - "bash_aliases"

dot_nvim_files:
  - "init.lua"
  - "lua/commands.lua"
  - "lua/keymaps.lua"
  - "lua/options.lua"
  - "lua/plugins.lua"
  - "lsp/ansible.lua"
  - "lsp/python.lua"
